### ISSUE TITLE
Не запускается на Android Studio 2.0 stable

### ISSUE THREAD

**Issue by root1991** [ermaq/second_tech_test#1]
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by ermaq** [comment]
Попробуйте еще раз. Вроде пофиксил.
